name: Swift CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Swift Packages
        uses: actions/cache@v4
        with:
          path: |
            .build
            SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build and test
        run: |
          xcodebuild test \
            -scheme swift-node-like-node-RED \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            -derivedDataPath .build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
