name: GitHub Actions Demo App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Test On iOS Simulator
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode_16.4.app

      - name: Build
        run: xcodebuild -scheme ArticleSearcher -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5'

      - name: Run Tests
        run: xcodebuild -scheme ArticleSearcher -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5' test
